### ISSUE TITLE
No Issue - Just a question

### ISSUE THREAD

**Issue by shpendk** [TheRook/subbrute#13]
Hi Guys,

First of all, great work. A really useful piece of code. I wanted to ask if you guys would mind if i create a burp extension out of this script? I understand its GNU license, and i plan to keep the extension open source aswell, just want to get your guys consent. 

Let me know.

**Comment by TheRook** [comment]
Go for it,  I like BURP and a mashup would be neat.

**Comment by TheRook** [comment]
Another problem solved.

**Comment by shpendk** [comment]
Thanks man, I'll let you know when its ready :)
