### ISSUE TITLE
#NoIssue - 1.313 new subdomain names

### ISSUE THREAD

**Issue by 8vw** [TheRook/subbrute#14]
Hi guys!
Thanks to share this tool, is really useful.
I kept my own list where i was updating (from fierce and others).
So, when i saw the "names.txt" i just merged (cat names.txt MyOwn.txt | sort | uniq > subdomains.txt)
with my own list and now i have a new subdomain list with 32611 lines.
Just take it (subdomains.txt) from my GitHub page, here:

https://github.com/8vw/s0nar (And yes, feel free to use s0nar ;) 

best regards

@8vw

**Comment by TheRook** [comment]
Thanks for the new names.  SubBrute's name list is sorted by frequency, so that the user starts to get results quickly,  it also means that it is difficult to merge new lists.  We have a few other name lists that need to be merged.  Hopefully we can get this together soon.

**Comment by bishopfox003** [comment]
added to names_large.txt

**Comment by TheRook** [comment]
Added to names_large.txt
