### ISSUE TITLE
Rejected nameserver - wildcard

### ISSUE THREAD

**Issue by chris-h1** [TheRook/subbrute#20]
I just started subbrute on ubuntu 12.04:
./subbrute.py -v -s names_small.txt sony.com

and get just tons of
---8<---
wildcard exception: ['216.52.65.1'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 216.52.65.1 
wildcard exception: ['72.37.141.91'] <class 'dns.resolver.NoNameservers'> 
Rejected nameserver - wildcard: 72.37.141.91 
wildcard exception: ['216.52.97.33'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 216.52.97.33 
wildcard exception: ['106.51.255.133'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 106.51.255.133 
wildcard exception: ['164.2.255.241'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 164.2.255.241 
wildcard exception: ['91.203.188.1'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 91.203.188.1 
wildcard exception: ['203.253.64.1'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 203.253.64.1 
wildcard exception: ['186.107.119.118'] <class 'dns.exception.Timeout'> 
Rejected nameserver - wildcard: 186.107.119.118 
wildcard exception: ['206.126.32.101'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 206.126.32.101 
wildcard exception: ['217.149.155.180'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 217.149.155.180 
wildcard exception: ['205.172.19.193'] <class 'dns.resolver.NoAnswer'> 
Rejected nameserver - wildcard: 205.172.19.193 
...
---8<---
Why is that?
It seams the DNS-Servers don't answer to these enumerations.

Thanks,
Chris

**Comment by TheRook** [comment]
That is a very good question.  It looks like sony.com has strange configuration,  because even dig is having trouble:
dig A sony.com @206.126.32.101

However,  google's DNS server works:
dig A sony.com@8.8.8.8 

...and so does this:
dig ANY sony.com @8.8.8.8

I am working on porting subbrute over to dnslib with ANY meta reqeusts,  and I think that this change will inadvertently solve this oddity.  Thanks for the report, I will use this as a test case.  Hang tight,  and I should have a new version out within the week.

**Comment by ss23** [comment]
If you needed another test case, `apple.com` seems to produce the same behaviour.
At the same time, just for curiosities sake, if you happen to figure out why this doesn't work properly for some domains, it might be interesting to know that too.

**Comment by TheRook** [comment]
Solved this issue in SubBrute 2.0 by building a unique wildcard fingerprint per-server.  This includes the DNS record "rcode" returned by the resolver for a  failed lookup.  sony.com uses "NOERROR" instead of "NXDOMAIN" as the "rcode" for failed lookups.
