### ISSUE TITLE
Not able to import dnslib from Kali

### ISSUE THREAD

**Issue by thricegr8est** [TheRook/subbrute#25]
# uname -a: Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

# python -V : 2.7.3

# python subbrute.py google.com: Traceback (most recent call last):
  File "subbrute.py", line 10, in <module>
    import dnslib
ImportError: No module named dnslib

Thanks

**Comment by TheRook** [comment]
pip install dnslib
or
apt-get install python-dnslib
