### ISSUE TITLE
Unable to find authoritative resolvers for:google.com

### ISSUE THREAD

**Issue by ronnieflip** [TheRook/subbrute#34]
First time using this tool however i can't seem to get it working both in windows 8 and kali 2.0. Gives me the same error nomatter what domain i try:

Unable to find authoritative resolvers for:cnn.com

I've tried the windows exe but it just freezes forever.

**Comment by TheRook** [comment]
Interesting bug report.  I think this is a valid issue,  try changing the resolvers to your ISP,  does this fix the problem?  

With your limited connection, can you resolve on 8.8.8.8?
dig google.com @8.8.8.8

**Comment by mehranexpert** [comment]
same error " Unable to find authoritative resolvers for:google.com "

i also changed resolvers.txt to my ISP Resolver .

dig google.com @8.8.8.8

; <<>> DiG 9.9.5-9+deb8u2-Debian <<>> google.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17239
;; flags: qr rd ra; QUERY: 1, ANSWER: 11, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		172	IN	A	173.194.116.201
google.com.		172	IN	A	173.194.116.206
google.com.		172	IN	A	173.194.116.192
google.com.		172	IN	A	173.194.116.199
google.com.		172	IN	A	173.194.116.200
google.com.		172	IN	A	173.194.116.195
google.com.		172	IN	A	173.194.116.194
google.com.		172	IN	A	173.194.116.193
google.com.		172	IN	A	173.194.116.198
google.com.		172	IN	A	173.194.116.196
google.com.		172	IN	A	173.194.116.197

;; Query time: 204 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Apr 03 04:51:48 EDT 2016
;; MSG SIZE  rcvd: 215

**Comment by manuelbua** [comment]
I'm hitting the same problem after switching to Google's `8.8.8.8/8.8.4.4` nameservers: i currently avoid this error by using OpenDNS instead `echo -e "208.67.222.222\n208.67.220.220" > opendns.txt`.

**Comment by pepa65** [comment]
I have the same problem, any domain I try, like:
python subbrute.py google.com
"Unable to find authoritative resolvers for: google.com"
It can't have anything to do with any ISP I would think.

**Comment by TheRook** [comment]
Does dig work with TCP,  or only UDP?

>dig NS +tcp google.com @8.8.8.8

The command above and subbrute work great on mysystem, which makes this
issue exceeding difficult to patch.  I'd be happy to merge a pull request
if you can figure out why it won't work on your systems

subbrute> python subbrute.py google.com -p
google.com,A,216.58.194.206
google.com,AAAA,2607:f8b0:4005:805::200e
google.com,MX,50 alt4.aspmx.l.google.com.
google.com,MX,10 aspmx.l.google.com.
google.com,NS,ns3.google.com.
google.com,NS,ns2.google.com.
google.com,NS,ns4.google.com.
...

**Comment by pepa65** [comment]
`dig NS +tcp google.com @8.8.8.8`
;; Connection to 8.8.8.8#53(8.8.8.8) for google.com failed: connection refused.

**Comment by ronnieflip** [comment]
@pepa65 Try hooking to a different network, preferably with a different ISP and share the result. I honest failed to understand this but all i can say is that it worked with no problem after switching my ISP.

**Comment by TheRook** [comment]
If your ISP is blocking access to the resolvers with -r, then all I can do
for you is VPN access XD

Good luck guys.
