### ISSUE TITLE
Lockup on network connectivity lost

### ISSUE THREAD

**Issue by dwendt** [TheRook/subbrute#35]
Hey, I noticed that when I was testing through a tunnel that would go in/out about hourly that subbrute would lock up and stop sending requests even when connection is regained. Is it possible to differentiate between a lost connection and just not receiving responses? I'm thinking maybe if there's transmission failures for the last X, delay for Y and repeat them to see if they succeed. Not sure if this'd trigger false positives for rate-limiting servers though.

**Comment by TheRook** [comment]
Ahh!  I have seen this before, and I think its a known bug in DNSLib 0.9.6. I stepped though this condition with a debugger and subbrute will hang when reading from the socket - the socket timeout is ignored in some cases.  I dug into DNSLib a bit - and this issue needs to be revisited.

**Comment by TheRook** [comment]
updated dnslib,  i think this will work.
