### ISSUE TITLE
Filtering known false positives

### ISSUE THREAD

**Issue by theforcedk** [TheRook/subbrute#36]
Hi there

Great tool; question. Is it possible/planned/how would i, filter out responses that I know are false positives? The domain I'm testing against has a \* record set up, and all domains (fsdkfjsdfsd.domain.com) responds with "This domain is not associated with an application.". The response is a HTTP 400 (bad request) header, and not a 200 OK, so that would be a way to test it, and/or regex matching contents but that might take a bit longer to process.

Possible?

**Comment by decidedlygray** [comment]
This would be tricky, might not be possible. If you add a * to your names.txt you can see if a wildcard exists, but not if your queries are being answered by a wildcard. Additional details here: [http://serverfault.com/questions/160716/how-can-i-determine-whether-xyz-example-com-uses-a-wildcard-a-record](http://serverfault.com/questions/160716/how-can-i-determine-whether-xyz-example-com-uses-a-wildcard-a-record)

**Comment by theforcedk** [comment]
I figured as much. Entries will need to checked manually/via. other application - all good, just wondering. Thanks a lot!
